server:
  AppVersion: 1.0.0
  Port: :5000
  Mode: Development
  ProcessTimeout: 60
  ReadTimeout: 5
  WriteTimeout: 5
  MigrateOnStart: true
  TimeZone: Asia/Ho_Chi_Minh

jwt:
  # JwtSecretKey: 9056b94a8611363c2c43aa3760d65a48c834744b877b5041fa99a919d5aaf635
  JwtIssuer: stockk-go
  JwtAccessTokenExpireDuration: 15
  JwtAccessTokenPrivateKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUNnc2RDdU92MGJDY1FCbjJxOWhIa1U5MWhscFMxWVJNRnBib1VROEI3VkxjVU9LMGMxCmc3TGdNYzh0d2VwQzcvNisweWFkZzIxN1NlNWw2M2RoK0xzZVgwUEQ0ckhtUm1HaW8rbks3ei9wZW9MMUY1a1AKbVc5UU9vQ1NUU3hrTE51RUFYUSt3NmtuMXJiSlpFMlprU1pwLzBRZ2pOckFWTm9OQ2ttVjdHZGdNd0lEQVFBQgpBb0dBUlZPeGhobG83T3RQcHF1U0wyVWhuOHYrVlF2bi9qYmJncEx0MFpybWttNEduOUJJRG14ZEZhQW5rOFFmClB2V3ZYOEJVM291L0JmdWxZRTh2MkJLcEZ3UEpaeTFETWNpY3R2ZDlhUVo0ekI1bFZ4Wk85UWFONVpnSCtWbDAKQjVTNE9mWEtZZFFnTDBiUU1NMmlDclpMVTJaVEJ4YlNDMlUrRkNYVG5LUk45eUVDUVFEK3pYcWI4UXpIemUzYwpHWCt6TkVNOVp6NE9SUG5tK0FyY1hHQksxTkJMWkxJZkVvMG5xUlFBVUMzYit3QjhZOFdqYi9EZWNIUnpleFJYClNvZEVxaWQ3QWtFQW9YTWdhdVVBdUI4T0VsenJmdlZEREM4WWhJblJtRytFNlVFL084bTB5NUtjT29mZXRvd1oKRDlQbFdDb2FyajlwbE9jclZpNG45YU9nV1VDeVJERHdxUUpBTHBuQi9OYy9NU08yaHZTYTZGbDhtclJSSXliMgpWWW16NHMxNlJ2VlpDeERsaXMxSHg2TWlwMVFDcnlMZTJlRWRlbUMwdXRueVVsU0dTZGkxbUpkT0ZRSkFjZ2V1ClRkR1F3SHF1cGFtYmF3QXZhdHVZcFlQeDFZaHVoNURkNkl4K2RZb0hiZytvN2FYbHpaZ0wxRWxvcnNsNitRQ04KUzBFdVdBQkpzTUJSS0hpb2dRSkJBTGhvTUVTZG40UHgrWjE2VWw3Q3B4RTdudjR6anYyTVlRazhzUXRySjl6WgpjVmdCVHJ5YTFsdzhkampmL0pUbS9ZQ2pCOGFYWis4SGdRajlHbVloZmNJPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
  JwtAccessTokenPublicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDZ3NkQ3VPdjBiQ2NRQm4ycTloSGtVOTFobApwUzFZUk1GcGJvVVE4QjdWTGNVT0swYzFnN0xnTWM4dHdlcEM3LzYrMHlhZGcyMTdTZTVsNjNkaCtMc2VYMFBECjRySG1SbUdpbytuSzd6L3Blb0wxRjVrUG1XOVFPb0NTVFN4a0xOdUVBWFErdzZrbjFyYkpaRTJaa1NacC8wUWcKak5yQVZOb05Da21WN0dkZ013SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
  JwtRefreshTokenExpireDuration: 1440
  JwtRefreshTokenPrivateKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUNleFpvelpTa0Q1ZFgwY084ZDlyZ3dpNDdFMGhpekVaTDFOWFVkOWpjRkRXK0FnOTlzCjVhRk1PMWxwSVlhZXFkOXBZQzloNHlnMUNYNVhqT1BORjNDLzZNem5STWJNZlNtMW96ZTBwMUREd0FtNzF1dUsKVzExaFdVZDFOMkZ0M3czMjZoWEZuZDhUaFM5NkxreTFrM0R2bHRmY3JlYjdHTVdRNWwyRzdITFN6d0lEQVFBQgpBb0dBTTkrVHRkOERPNGJJRklraFZzVFpBT05YemU1bXEzcStiT2IrVUwrMDBpM0ZsRk9CbCs2ZWVHMmJsTUdqClhndGFOdTk2QzUxUDhhUWNaelpjNXhFVmdOZlR3MU0yOEN1ZGQ2UkNiUFpVOW9TUjM3ZlFsN1lVNFNwWmQ5RzAKbER6VExWMlZVSGxpUWhYOUx4dHQxZ3d0U2JKUUxaNGdLNTFEQzZjLzlFRmpkc0VDUVFEemRoRjV1ZWZFRnBiLwpjQk5oUzlkeTVxbEI0Y1NWY0s3UW5ZU0RlRzd1NW5BNS92RnVOKzU2WjN4TktFYXFZUFRBeUp6OGdjak5xeDVCCjdFb0tMNzFYQWtFQXB2THhFSnRSMDNRcHFwZ0g1TjNMQzZsbjRSODBCY01aamlITzVyM3ViQktOblBtNk84UjMKaVBMZ1hXeTVsajFqMEZpY2NYdEZLcVdteWw4RjN0NnpTUUpBRXJGMkZncVlLUTR5K2RuNUl2ZFh5NUs2WER5aApnM2ZyZEVrajY1UkxzRHd4VWNLcGR2VUVjcEdQa2IwTjcvY1IwOXVUY2kvazR5WElaUGRubC9DaWNRSkFGbXJJCnM5SW5TcDF1ZXRtdk5hd1NkNTVudEhMY0tXbnBKSXlsbTVZbFRaMndKa1BpSGVSanFKLzBRSmM0MUZPcDgyL3kKa2NwYm56NWZCdzE3WEZITEFRSkJBT0laYlN1aWFWa2tJZGNUM29KVzlpdTZZdUVic1kyZHVwRjVhenNhNGhuYwptaWJIcVNYdW5VaHZ3L2ZOWDZmVktuaHZJR0pFcHFaUFczTnhvbktjYzhFPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
  JwtRefreshTokenPublicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDZXhab3paU2tENWRYMGNPOGQ5cmd3aTQ3RQowaGl6RVpMMU5YVWQ5amNGRFcrQWc5OXM1YUZNTzFscElZYWVxZDlwWUM5aDR5ZzFDWDVYak9QTkYzQy82TXpuClJNYk1mU20xb3plMHAxRER3QW03MXV1S1cxMWhXVWQxTjJGdDN3MzI2aFhGbmQ4VGhTOTZMa3kxazNEdmx0ZmMKcmViN0dNV1E1bDJHN0hMU3p3SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==

firstSuperUser:
  FirstSuperUserEmail: root@gmail.com
  FirstSuperUserName: root
  FirstSuperUserPassword: root_password

logger:
  LoggerEncoding: console
  LoggerLevel: debug

postgres:
  PostgresqlHost: db
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: db

redis:
  RedisAddr: redis:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

email:
  EmailFrom: admin@admin.com
  EmailName: Stockk go
  EmailLink: https://stockk-go.com
  EmailLogoLink: https://media.vov.vn/sites/default/files/styles/front_large/public/2022-12/nhung-dieu-thu-vi-ve-logo-apple-ma-ban-chua-biet-4.png
  EmailCopyright: Copyright Â© 2017 example inc. All rights reserved.
  EmailVerificationSubject: Your account verification code
  EmailResetSubject: Your account password reset token

smtpEmail:
  SmtpHost: sandbox.smtp.mailtrap.io
  SmtpPort: 2525
  SmtpUser: 1fa73a84091130
  SmtpPassword: 9a817b2133d80c
  SmtpUseTls: true
  SmtpUseSsl: false

influxDB:
  InfluxDBHost: influxdb
  InfluxDBPort: 8086
  InfluxDBUsername: admin
  InfluxDBPassword: admin1234
  InfluxDBToken: 905d9eaf34914b43ac13fcba47851324ba9887d1b01dc2e866bf4acacc30819c
  InfluxDBOrg: history

taskRedis:
  TaskRedisAddr: redis:6379
  TaskRedisDb: 1

crawler:
  CrawlerSource: SSI
  CrawlerTickerDownloadBatchSize: 5
  CrawlerTickerInsertBatchSize: 5
  CrawlerBarInsertBatchSize: 5
  CrawlerDefaultActive:
    [
      "ACB",
      "ANV",
      "ASM",
      "BCC",
      "BCG",
      "BCM",
      "BID",
      "BMI",
      "BSR",
      "BVH",
      "C4G",
      "CII",
      "CMX",
      "CNG",
      "CTD",
      "CTG",
      "CTR",
      "DBC",
      "DCM",
      "DGC",
      "DGW",
      "DHA",
      "DIG",
      "DPM",
      "DPR",
      "DRC",
      "DRI",
      "DXG",
      "DXS",
      "FCN",
      "FMC",
      "FPT",
      "FRT",
      "FTS",
      "GAS",
      "GEG",
      "GIL",
      "GMD",
      "GVR",
      "HAG",
      "HAH",
      "HAX",
      "HBC",
      "HCM",
      "HDB",
      "HDC",
      "HDG",
      "HHV",
      "HPG",
      "HSG",
      "HT1",
      "HTN",
      "IDC",
      "KBC",
      "KDC",
      "KDH",
      "KSB",
      "LCG",
      "LPB",
      "LTG",
      "MBB",
      "MBS",
      "MIG",
      "MSB",
      "MSH",
      "MSN",
      "MWG",
      "NKG",
      "NLG",
      "NT2",
      "NVL",
      "OCB",
      "OIL",
      "PAN",
      "PC1",
      "PDR",
      "PET",
      "PHR",
      "PLC",
      "PLX",
      "PNJ",
      "POW",
      "PVD",
      "PVS",
      "PVT",
      "REE",
      "SAB",
      "SBT",
      "SGP",
      "SHB",
      "SHS",
      "SSI",
      "STB",
      "SZC",
      "TAR",
      "TCB",
      "TNG",
      "TPB",
      "VCB",
      "VCG",
      "VCI",
      "VGC",
      "VGT",
      "VHC",
      "VHM",
      "VIB",
      "VIC",
      "VJC",
      "VND",
      "VNM",
      "VPB",
      "VRE",
      "VTP",
    ]
